name: Hempfield Area Band
favicon: null
layout_spectrum: 0.13439
typography_spectrum: 0.38815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b7c7da'
    - '#060606'
    - '#9b928b'
    - '#565c58'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
