name: Hempfield Area Band
favicon: null
layout_spectrum: 0.2663179615046829
typography_spectrum: 0.8124672949779779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0e'
    - '#4a4142'
    - '#f0eff4'
    - '#3571b6'
    - '#bf9386'
  brandStrength: 0.6229170772712678
  lightness: 0.2826308626681566
  saturation: 0.869321916019544
  rhythmicContrast: 0.7094914501067251
purpose: []
