name: Hempfield Area Band
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#447fc3'
    - '#9cbcdf'
    - '#ffffff'
    - '#5f3312'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
