name: Hempfield Area Band
favicon: null
layout_spectrum: 0.47329
typography_spectrum: 0.38815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#556231'
    - '#fdc89f'
    - '#e88b57'
    - '#1f7bdc'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
