name: Hempfield Area Band
favicon: null
layout_spectrum: 0.00083
typography_spectrum: 0.38815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f19f3b'
    - '#443789'
    - '#039fd8'
    - '#e0434c'
  brandStrength: 0.4375
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
